#--------------------------------------------
#--------------------------------------------
# Configuration file for Stweeler
#--------------------------------------------
#--------------------------------------------

#tweeter credentials
consumer_key: 'EQ4KxfH5SxcQVIdPTKkfGt4cx'
consumer_secret: '5UR0H3zDNZuaiZVnVO8tDYRcaYDCk8YD0Ap4RKxgTIIWGBzkkj'
oauth_token: '3047040941-FaL1TjE4Js1zCUkknPFpKP5DIA9q4IHRMMLr9JO'
oauth_token_secret: 'kp9hWfsMqyvpkr2DNUiYLISFkRthNx0dHKfr6g5RUkUih'

#--------------------------------------------
#--------------------------------------------

#storage properties
storage_folder: '/local/scratch/twitter-data'
#storage_folder: '.'

#--------------------------------------------
#--------------------------------------------

#bot options
# 40 bots per hour, i.e. 1008 follows per day
follow_number: 40
follow_frequency: 1

unfollow_number: 100
unfollow_frequency: 3

