#--------------------------------------------
#--------------------------------------------
# Configuration file for Stweeler
#--------------------------------------------
#--------------------------------------------

#tweeter credentials
consumer_key: 'EQ4KxfH5SxcQVIdPTKkfGt4cx'
consumer_secret: '5UR0H3zDNZuaiZVnVO8tDYRcaYDCk8YD0Ap4RKxgTIIWGBzkkj'
oauth_token: '3047040941-FaL1TjE4Js1zCUkknPFpKP5DIA9q4IHRMMLr9JO'
oauth_token_secret: 'kp9hWfsMqyvpkr2DNUiYLISFkRthNx0dHKfr6g5RUkUih'

#--------------------------------------------
#--------------------------------------------

#storage properties
storage_folder: '/local/scratch/twitter-data'
#storage_folder: '.'

#--------------------------------------------
#--------------------------------------------

#bot options
# 15 follows each 15 min. i.e., 1440 follows per day
follow_number: 15
#in minutes
follow_frequency: 15

#will unfollow until the follower ratio is: 
follower_ratio: 0.3
#unfollow will occur every N hours:
unfollow_frequency: 48

