#--------------------------------------------
#--------------------------------------------
# Configuration file for Stweeler
#--------------------------------------------
#--------------------------------------------

#tweeter credentials
consumer_key: 'JPW5zRFRWWiJz74R9RTRw0DnD'
consumer_secret: '3loS6buCjB6RzQ3xkg81nrgp7VYc7kgh93z9imyUfOFp2wYHYH'
oauth_token: '3047040941-ilKIO4fy2mw0P5WzzvE1ngN7VZbthkbgDyKjWIH'
oauth_token_secret: 'raxJIpqRGjXYYBA1rw7ePhyH84IjL975rAWdJVW3Apb1b'

#--------------------------------------------
#--------------------------------------------

#storage properties
storage_folder: '/local/scratch/twitter-data'
#storage_folder: '.'

#--------------------------------------------
#--------------------------------------------

#bot options
# 40 bots per hour, i.e. 1008 follows per day
follow_number: 40
follow_frequency: 1

unfollow_number: 100
unfollow_frequency: 3

